### ISSUE TITLE
Opening "Options" in pause menu corrupts the HUD screen graphics

### ISSUE THREAD

**Issue by mariomadproductions** [mariomadproductions/nsmb-e3-rec#1]
Opening the "Options" sub-menu in the pause menu then closing it corrupts the HUD. Exiting the level or resetting the game fixes this. Solution: remove the "Options" entry from the pause menu. The demo probably only had "Continue" and "Quit" anyway. Maybe the options menu could be accessable from the menu screen via a key combo, even if that wasn't part of the demo.

**Comment by TheGameratorT** [comment]
Fixed when changed pause menu to MvsL pause menu.
