### ISSUE TITLE
The ! block sometimes makes Mario invisible

### ISSUE THREAD

**Issue by calmsacibis995** [mariomadproductions/nsmb-e3-rec#12]
![2021-10-27 15 23](https://user-images.githubusercontent.com/46319359/139068709-37fb3552-995b-4280-b760-9f68ec7a82c8.jpg)

I was playing the fortress level, when I tried hitting the ! block after it turned green, it made me invisible.

**Comment by TheGameratorT** [comment]
Same issue as #6, apparently it didn't get fixed.
My proposed solution is to rewrite everything lmao.

**Comment by mariomadproductions** [comment]
Closing this to stay organised - instead #6 can be used.
